<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<LangVersion>latest</LangVersion>
		<IsPackable>true</IsPackable>
		<PackageId>ThrottleDebounce.SourceGenerators</PackageId>
		<Version>1.0.2</Version>
		<Authors>Carlos</Authors>
		<Description>Prism MVVM ThrottleDebounceCommandGenerator</Description>
		<RepositoryUrl>https://github.com/zh-coder-carlos/Prism.ThrottleDebounce.SourceGenerators.git</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageOutputPath>$(MSBuildProjectDirectory)\nupkg</PackageOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ThrottleDebounce" Version="2.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Link="analyzers\%(Filename)%(Extension)" Visible="false" />
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="lib/netstandard2.0" Link="lib\%(Filename)%(Extension)" Visible="false" />
	</ItemGroup>
</Project>
