using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Prism.ThrottleDebounce.SourceGenerators
{
    [Generator]
    public class ThrottleDebounceCommandGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not SyntaxReceiver receiver) return;

            foreach (var methodDeclaration in receiver.CandidateMethods)
            {
                var semanticModel = context.Compilation.GetSemanticModel(methodDeclaration.SyntaxTree);
                var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;

                if (methodSymbol == null) continue;

                var attrData = methodSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() is
                        "Prism.ThrottleDebounce.SourceGenerators.DebounceCommandAttribute" or
                        "Prism.ThrottleDebounce.SourceGenerators.ThrottleCommandAttribute");

                if (attrData == null) continue;

                var delayMs = attrData.ConstructorArguments[0].Value?.ToString() ?? "300";
                var isDebounce = attrData.AttributeClass!.ToDisplayString() ==
                                 "Prism.ThrottleDebounce.SourceGenerators.DebounceCommandAttribute";

                var leading = attrData.NamedArguments.FirstOrDefault(x => x.Key == "Leading").Value.Value?.ToString()?.ToLower() ?? (isDebounce ? "false" : "true");
                var trailing = attrData.NamedArguments.FirstOrDefault(x => x.Key == "Trailing").Value.Value?.ToString()?.ToLower() ?? "true";

                var classSymbol = methodSymbol.ContainingType;
                var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
                var className = classSymbol.Name;
                var methodName = methodSymbol.Name;
                var commandName = $"{methodName}Command";

                var parameters = methodSymbol.Parameters;
                bool hasParameter = parameters.Length > 0;

                string paramList = "";
                string delegateParamList = "";
                string genericArgs = "";

                if (hasParameter)
                {
                    var paramDetails = parameters.Select(p => (
                        Type: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        Name: p.Name));

                    paramList = string.Join(", ", paramDetails.Select(p => p.Name));
                    delegateParamList = string.Join(", ", paramDetails.Select(p => $"{p.Type} {p.Name}"));
                    genericArgs = "<" + string.Join(", ", paramDetails.Select(p => p.Type)) + ">";
                }

                string generatedCode = $@"
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace {namespaceName}
{{
    partial class {className}
    {{
        public global::Prism.Commands.DelegateCommand{genericArgs} {commandName} => field ??= new global::Prism.Commands.DelegateCommand{genericArgs}(
            ThrottleDebounce.{(isDebounce ? "Debouncer" : "Throttler")}.{(isDebounce ? "Debounce" : "Throttle")}(
                new System.Action{genericArgs}(({delegateParamList}) => {methodName}({paramList})), 
                System.TimeSpan.FromMilliseconds({delayMs}), 
                leading: {leading}, 
                trailing: {trailing}
            ).Invoke
        );
    }}
}}";
                context.AddSource($"{className}.{methodName}.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        }

        private class SyntaxReceiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> CandidateMethods { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is MethodDeclarationSyntax methodSyntax && methodSyntax.AttributeLists.Count > 0)
                {
                    bool hasTargetAttribute = methodSyntax.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .Any(a => a.Name.ToString() is "DebounceCommand" or "ThrottleCommand"
                                             or "DebounceCommandAttribute" or "ThrottleCommandAttribute");

                    if (hasTargetAttribute)
                    {
                        CandidateMethods.Add(methodSyntax);
                    }
                }
            }
        }
    }
}